services:
  db:
    container_name: hitogoto-db
    image: postgres:15
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=hitogoto
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:latest
    container_name: hitogoto-minio
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: admin123
    command: server --console-address ":9090" /data
    volumes:
      - ./docker/minio/data:/data
    ports:
      - 9000:9000
      - 9090:9090